server:
  port: ${APP_PORT}

keycloak-admin:
  url: ${KEYCLOAK_BASE_URL}
  realm: ${REALM_NAME}
  client-id: admin-cli
  client-secret: ${ADMIN_CLI_SECRET}

keycloak:
  auth-server-url: ${KEYCLOAK_BASE_URL}
  realm: ${REALM_NAME}
  resource: otus-app
  public-client: true
  credentials:
    secret: ${OTUS_APP_SECRET}
  enable-basic-auth: true
  bearer-only: true

management:
  endpoint:
    health:
      show-details: always
  metrics:
    distribution:
      slo:
        http.server.requests: 10ms, 50ms, 100ms, 200ms, 300ms, 400ms, 500ms
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.security: DEBUG

springdoc:
  api-docs:
    path: /openapi
  show-actuator: true
  swagger-ui:
    path: swagger-ui.html
    disable-swagger-default-url: true