server:
    port: ${APP_PORT}
spring:
    datasource:
        driverClassName: org.postgresql.Driver
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL9Dialect
        open-in-view: false
        show-sql: true
        generate-ddl: false
        hibernate:
            ddl-auto: validate
    liquibase:
        drop-first: false
        change-log: classpath:db/changelog/db.changelog-master.xml
        enabled: true
        default-schema: public

springdoc:
    api-docs:
        path: /openapi
    show-actuator: true
    swagger-ui:
        path: swagger-ui.html
        disable-swagger-default-url: true