{
 "title": "Home work 6",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Quantiles by URI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by (uri, method, le) (rate(http_server_requests_seconds_bucket{uri=~\"/api/.*|/auth/.*\"}[1m])))",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (uri, method, le) (rate(http_server_requests_seconds_bucket{uri=~\"/api/.*|/auth/.*\"}[1m])))",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (uri, method, le) (rate(http_server_requests_seconds_bucket{uri=~\"/api/.*|/auth/.*\"}[1m])))",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "50",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (uri, method, le) (rate(http_server_requests_seconds_bucket{uri=~\"/api/.*|/auth/.*\"}[1m])))",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  { "title": "RPS by URI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (method, uri) (rate(http_server_requests_seconds_count{uri=~\"/api/.*|/auth/.*}\"}[1m]))",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  { "title": "Error rate by URI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "5xx error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum by (uri, method) (rate(http_server_requests_seconds_count{uri=~\"/api/.*|/auth/.*\", status=~\"5.*\"}[1m]))",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Quantiles from nginx-ingress-controller",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 }
  },
  {
   "title": "max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n    1, sum by (\r\n        method, host, le\r\n    ) (\r\n        rate(\r\n            nginx_ingress_controller_request_duration_seconds_bucket[1m]\r\n        )\r\n    )\r\n)",
     "legendFormat": "{{method}} {{host}}"
    }
   ]
  },
  {
   "title": "99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n    0.99, sum by (\r\n        method, host, le\r\n    ) (\r\n        rate(\r\n            nginx_ingress_controller_request_duration_seconds_bucket[1m]\r\n        )\r\n    )\r\n)",
     "legendFormat": "{{method}} {{host}}"
    }
   ]
  },
  {
   "title": "95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n    0.95, sum by (\r\n        method, host, le\r\n    ) (\r\n        rate(\r\n            nginx_ingress_controller_request_duration_seconds_bucket[1m]\r\n        )\r\n    )\r\n)",
     "legendFormat": "{{method}} {{host}}"
    }
   ]
  },
  {
   "title": "50",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n    0.5, sum by (\r\n        method, host, le\r\n    ) (\r\n        rate(\r\n            nginx_ingress_controller_request_duration_seconds_bucket[1m]\r\n        )\r\n    )\r\n)",
     "legendFormat": "{{method}} {{host}}"
    }
   ]
  },
  {
   "title": "RPS from nginx-ingress-controller",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 }
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (method, host) (rate( nginx_ingress_controller_request_duration_seconds_count[1m]))",
     "legendFormat": "{{method}} {{host}}"
    }
   ]
  },
  {
   "title": "Error rate from nginx-ingress-controller",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 }
  },
  {
   "title": "5xx error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "sum by (method, host) (rate(nginx_ingress_controller_request_duration_seconds_count{status=~\"5.*\"}[1m]))",
     "legendFormat": "{{method}} {{host}}"
    }
   ]
  }
 ]
}