applicationName: home-work
applicationLabels: home-work
replicaCount: 3

image:
  repository: quadro5/home-work
  pullPolicy: IfNotPresent
  tag: "0.4.0"

pod:
  containerPort: 8000

service:
  type: ClusterIP
  port: 80

ingress:
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  hosts:
    - host: arch.homework
      paths:
        - path: /(.*)
          pathType: Prefix
          backend:
            service:
              name: home-work-service
              port:
                number: 80