apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.applicationName }}-deployment
  labels:
    app: {{ .Values.applicationName }}-deployment
  namespace: {{ .Values.ns }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.applicationName }}-app
  template:
    metadata:
      labels:
        app: "{{ .Values.applicationName }}-app"
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.pod.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.pod.containerPort }}
            initialDelaySeconds: {{ .Values.pod.initialDelaySeconds }}
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.pod.containerPort }}
            initialDelaySeconds: {{ .Values.pod.initialDelaySeconds }}
            periodSeconds: 5
          env:
            - name: DB_URL
              value: jdbc:postgresql://postgresql:5432/postgres
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: dbPassword
                  optional: false
          envFrom:
            - configMapRef:
                name: {{ .Values.applicationName }}-config-map